// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("PostId", Name = "IX_PostId")]
public partial class Answer
{
    [Key]
    public int Id { get; set; }

    public string Answers { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AnswerDate { get; set; }

    public int PostId { get; set; }

    [InverseProperty("Answer")]
    public virtual ICollection<AnswerLike> AnswerLikes { get; set; } = new List<AnswerLike>();

    [ForeignKey("PostId")]
    [InverseProperty("Answers")]
    public virtual Post Post { get; set; }

    [NotMapped]
    public int Likes { get; set; }
}