// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("AnswerId", Name = "IX_AnswerId")]
[Index("UserId", Name = "IX_UserId")]
public partial class AnswerLike
{
    [Key]
    public int Id { get; set; }

    public int AnswerId { get; set; }

    public int UserId { get; set; }

    [ForeignKey("AnswerId")]
    [InverseProperty("AnswerLikes")]
    public virtual Answer Answer { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("AnswerLikes")]
    public virtual User User { get; set; }
}