// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("LessonId", Name = "IX_LessonId")]
[Index("UserId", Name = "IX_UserId")]
public partial class BlockedLecture
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    public int LessonId { get; set; }

    [ForeignKey("LessonId")]
    [InverseProperty("BlockedLectures")]
    public virtual Lesson Lesson { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("BlockedLectures")]
    public virtual User User { get; set; }
}