// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

public partial class Chat
{
    [Key]
    public int Id { get; set; }

    public int FromUserId { get; set; }

    public string FromUserName { get; set; }

    public int RoomId { get; set; }

    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [InverseProperty("Chat")]
    public virtual ICollection<ChatStatue> ChatStatues { get; set; } = new List<ChatStatue>();
}