// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("UserId", Name = "IX_UserId")]
public partial class Coupon
{
    [Key]
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Name { get; set; }

    public int ContentType { get; set; }

    public int ContentId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Coupons")]
    public virtual User User { get; set; }
}