// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("LevelId", Name = "IX_LevelId")]
public partial class Division
{
    [Key]
    public int Id { get; set; }

    public int LevelId { get; set; }

    public string Name { get; set; }

    [ForeignKey("LevelId")]
    [InverseProperty("Divisions")]
    public virtual Level Level { get; set; }

    [InverseProperty("Division")]
    public virtual ICollection<Notif> Notifs { get; set; } = new List<Notif>();
}