// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("ExamId", Name = "IX_ExamId")]
public partial class ExamDetail
{
    [Key]
    public int Id { get; set; }

    public int ExamId { get; set; }

    public string Question { get; set; }

    public string Image { get; set; }

    public string Answer1 { get; set; }

    public string Answer2 { get; set; }

    public string Answer3 { get; set; }

    public string Answer4 { get; set; }

    public string Answer5 { get; set; }

    public int RightAnswer { get; set; }

    public int QuestionTimer { get; set; }

    public string AnswerDescription { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("ExamDetails")]
    public virtual Exam Exam { get; set; }
}