// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("LessonId", Name = "IX_LessonId")]
[Index("MaterialId", Name = "IX_MaterialId")]
[Index("UserId", Name = "IX_UserId")]
public partial class Homework
{
    [Key]
    public int Id { get; set; }

    public int MaterialId { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    public int? DependancyId { get; set; }

    public int? DependancyType { get; set; }

    public int? LessonId { get; set; }

    [ForeignKey("LessonId")]
    [InverseProperty("Homeworks")]
    public virtual Lesson Lesson { get; set; }

    [ForeignKey("MaterialId")]
    [InverseProperty("Homeworks")]
    public virtual Material Material { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Homeworks")]
    public virtual User User { get; set; }
}