// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

public partial class LatestOffer
{
    [Key]
    public int OfferId { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [StringLength(255)]
    public string OfferDescription { get; set; }

    [StringLength(2083)]
    public string OfferUrl { get; set; }

    public string? FilePath { get; set; }

}