// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAccessLayer.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("LessonId", Name = "IX_LessonId")]
[Index("MaterialId", Name = "IX_MaterialId")]
[Index("UserId", Name = "IX_UserId")]
public partial class Lecture
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    public int MaterialId { get; set; }

    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public string Url { get; set; }
    public string Drive { get; set; }


    public int Price { get; set; }

    public int? DependancyId { get; set; }

    public EnumProductType? DependancyType { get; set; }

    public int? LessonId { get; set; }

    public int Priority { get; set; }

    public string LectureDescription { get; set; }

    [ForeignKey("LessonId")]
    [InverseProperty("Lectures")]
    public virtual Lesson Lesson { get; set; }

    [ForeignKey("MaterialId")]
    [InverseProperty("Lectures")]
    public virtual Material Material { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Lectures")]
    public virtual User User { get; set; }


    [NotMapped]
    public bool IsBought { get; set; }

    [NotMapped]
    public string DependancyName { get; set; }
}