// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("FacultyId", Name = "IX_FacultyId")]
public partial class Level
{
    [Key]
    public int Id { get; set; }

    public int FacultyId { get; set; }

    public string Name { get; set; }

    [InverseProperty("Level")]
    public virtual ICollection<Division> Divisions { get; set; } = new List<Division>();

    [ForeignKey("FacultyId")]
    [InverseProperty("Levels")]
    public virtual Faculty Faculty { get; set; }

    [InverseProperty("Level")]
    public virtual ICollection<Notif> Notifs { get; set; } = new List<Notif>();
}