// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("UserId", Name = "IX_userId")]
public partial class Material
{
    [Key]
    public int Id { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    public string Name { get; set; }

    [InverseProperty("Material")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("Material")]
    public virtual ICollection<Homework> Homeworks { get; set; } = new List<Homework>();

    [InverseProperty("Material")]
    public virtual ICollection<Lecture> Lectures { get; set; } = new List<Lecture>();

    [InverseProperty("Material")]
    public virtual ICollection<Life> Lives { get; set; } = new List<Life>();

    [InverseProperty("Material")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    [InverseProperty("Material")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Material")]
    public virtual ICollection<Questions2> Questions2s { get; set; } = new List<Questions2>();

    [JsonIgnore]
    public virtual User User { get; set; }
}