// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("FacultyId", Name = "IX_FacultyId")]
public partial class News
{
    [Key]
    public int Id { get; set; }

    public string Title { get; set; }

    public string Details { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public int? FacultyId { get; set; }

    [ForeignKey("FacultyId")]
    [InverseProperty("News")]
    public virtual Faculty Faculty { get; set; }
}