// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("DivisionId", Name = "IX_DivisionId")]
[Index("FacultyId", Name = "IX_FacultyId")]
[Index("LevelId", Name = "IX_LevelId")]
public partial class Notif
{
    [Key]
    public int Id { get; set; }

    public string Title { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public int? FacultyId { get; set; }

    public int? LevelId { get; set; }

    public int? DivisionId { get; set; }

    [ForeignKey("DivisionId")]
    [InverseProperty("Notifs")]
    public virtual Division Division { get; set; }

    [ForeignKey("FacultyId")]
    [InverseProperty("Notifs")]
    public virtual Faculty Faculty { get; set; }

    [ForeignKey("LevelId")]
    [InverseProperty("Notifs")]
    public virtual Level Level { get; set; }
}