// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("UserId", Name = "IX_UserId")]
public partial class Payment
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public int Payed { get; set; }

    public int UserId { get; set; }

    public int ProductType { get; set; }

    public int BuyedItemId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BuyDate { get; set; }

    public int TrainerId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Payments")]
    public virtual User User { get; set; }
}