// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("MaterialId", Name = "IX_MaterialId")]
[Index("UserId", Name = "IX_UserId")]
public partial class Post
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public int MaterialId { get; set; }

    public int UserId { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [ForeignKey("MaterialId")]
    [InverseProperty("Posts")]
    public virtual Material Material { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    [ForeignKey("UserId")]
    [InverseProperty("Posts")]
    public virtual User User { get; set; }


    [NotMapped]
    public int Likes { get; set; }
}