// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("QuestionId", Name = "IX_QuestionId")]
[Index("UserId", Name = "IX_UserId")]
public partial class QuestionAnswer
{
    [Key]
    public int Id { get; set; }

    public int QuestionId { get; set; }

    public int UserId { get; set; }

    public int AnswerNumber { get; set; }

    [Column("isCorrect")]
    public bool IsCorrect { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AnswerDate { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("QuestionAnswers")]
    public virtual Question Question { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("QuestionAnswers")]
    public virtual User User { get; set; }
}