// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Table("Questions2")]
[Index("LessonId", Name = "IX_LessonId")]
[Index("MaterialId", Name = "IX_MaterialId")]
[Index("UnitId", Name = "IX_UnitId")]
public partial class Questions2
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public string Answer1 { get; set; }

    public string Answer2 { get; set; }

    public string Answer3 { get; set; }

    public string Answer4 { get; set; }

    public int CorrectAnswerNumber { get; set; }

    public string AnswerDescription { get; set; }

    public int MaterialId { get; set; }

    public int UnitId { get; set; }

    public int LessonId { get; set; }

    public string UnitText { get; set; }

    [ForeignKey("LessonId")]
    [InverseProperty("Questions2s")]
    public virtual Lesson Lesson { get; set; }

    [ForeignKey("MaterialId")]
    [InverseProperty("Questions2s")]
    public virtual Material Material { get; set; }

    [ForeignKey("UnitId")]
    [InverseProperty("Questions2s")]
    public virtual Unit Unit { get; set; }
}