// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

public partial class Room
{
    [Key]
    public int Id { get; set; }

    public string RoomName { get; set; }

    public int HostUserId { get; set; }

    public string ZoomUser { get; set; }

    public string ZoomPassword { get; set; }


    [NotMapped]
    public int UnReadMessages { get; set; }

    [NotMapped]
    public int NumberOfMembers { get; set; }
}