// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

public partial class Setting
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TimeFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TimeTo { get; set; }

    [NotMapped]
    public bool IsOpen { get; set; }
}