// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

public partial class Unit
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [InverseProperty("Unit")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("Unit")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Unit")]
    public virtual ICollection<Questions2> Questions2s { get; set; } = new List<Questions2>();
}